version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: promptsmith_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7.4-alpine


  backend:
    build:
      context: .
    command: "infra/scripts/start.sh"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=promptsmith_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your_django_secret
      - DEBUG='1'
      - JWT_SECRET=your_jwt_secret_here
      - ENABLE_DJANGO_ADMIN='0'
      - SITE_DOMAIN='localhost'
      - FRONTEND_DOMAIN='localhost'
      - USER_EMAIL='admin@localhost.lan'
      - USER_PASSWORD='AwesomePromptsManagement'
      - SITE_DOMAIN='localhost:8000'
      - FRONTEND_DOMAIN='localhost:3000'
    depends_on:
      - postgres
      - redis


  frontend:
    build:
      dockerfile: Dockerfile
      context: ./clients-side/frontend/prompt-smith-frontend/
    command: "node /app/server.js"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
      - API_URL=http://backend:8000
      - SESSION_SECRET=your_secret_key
      - NEXT_DEBUG=true   # Enable Next.js debug logging
      - DEBUG=*
      - NODE_ENV=development

volumes:
  postgres_data:
