# Generated by Django 5.1 on 2024-09-16 10:28

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import shared.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('unique_key', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=2048)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['unique_key'], name='core_prompt_unique__10145f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=256)),
                ('distinct_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=10000000)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_segmen_name_8d020c_idx'), django.contrib.postgres.indexes.GinIndex(fields=['distinct_ids'], name='core_segmen_distinc_247c6c_gin')],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(max_length=128)),
                ('model_name', models.TextField(blank=True, max_length=128, null=True)),
                ('content', models.TextField(max_length=1000000)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.prompt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prompt', 'name'), name='unique_prompt_version_name')],
            },
        ),
        migrations.CreateModel(
            name='PromptVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(default='A', max_length=2, validators=[shared.validators.validate_uppercase_letters])),
                ('percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('selected_version_uuid', models.UUIDField(blank=True, null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.prompt')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.segment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('prompt', 'name'), name='unique_prompt_variant_name')],
            },
        ),
    ]
