# Generated by Django 5.1 on 2024-08-27 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='unique_key',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='promptvariant',
            name='unique_key',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='model_name',
            field=models.TextField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='unique_key',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='segment',
            name='unique_key',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
