# Generated by Django 5.1 on 2024-09-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promptversion',
            name='core_prompt_name_2d7d7d_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptversion',
            name='core_prompt_model_n_b8c4a9_idx',
        ),
    ]
