# Generated by Django 5.1 on 2024-09-03 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptvariant',
            name='selected_version_key',
        ),
        migrations.RemoveField(
            model_name='promptvariant',
            name='unique_key',
        ),
        migrations.AddField(
            model_name='promptvariant',
            name='name',
            field=models.CharField(default='A', max_length=256),
        ),
        migrations.AddField(
            model_name='promptvariant',
            name='selected_version_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promptvariant',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='promptvariant',
            constraint=models.UniqueConstraint(fields=('prompt', 'name'), name='unique_prompt_variant_key'),
        ),
    ]
