# Generated by Django 5.1 on 2024-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptvariant',
            name='selected_version_uuid',
        ),
        migrations.AddField(
            model_name='promptvariant',
            name='selected_version_key',
            field=models.CharField(blank=True, null=True),
        ),
    ]
