# Generated by Django 5.1 on 2024-09-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promptversion_core_prompt_name_2d7d7d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promptvariant',
            name='unique_prompt_variant_key',
        ),
        migrations.RemoveIndex(
            model_name='prompt',
            name='core_prompt_enabled_f51741_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptvariant',
            name='core_prompt_prompt__fb0fa5_idx',
        ),
        migrations.RemoveIndex(
            model_name='promptversion',
            name='core_prompt_prompt__a6a6c7_idx',
        ),
        migrations.AddConstraint(
            model_name='promptvariant',
            constraint=models.UniqueConstraint(fields=('prompt', 'name'), name='unique_prompt_variant_name'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('prompt', 'name'), name='unique_prompt_version_name'),
        ),
    ]
