# Generated by Django 5.1 on 2024-09-03 09:24

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promptvariant_selected_version_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptvariant',
            name='name',
            field=models.CharField(default='A', max_length=2, validators=[shared.validators.validate_uppercase_letters]),
        ),
    ]
