# Generated by Django 5.1 on 2024-08-31 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_promptvariant_selected_version_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptvariant',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.prompt', to_field='unique_key'),
        ),
        migrations.AlterField(
            model_name='promptvariant',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.segment', to_field='unique_key'),
        ),
        migrations.AlterField(
            model_name='promptversion',
            name='prompt_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.promptvariant', to_field='unique_key'),
        ),
    ]
