# Generated by Django 5.1.1 on 2024-09-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_promptversion_model_name_and_more'),
        ('project', '0002_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
