# Generated by Django 5.1 on 2024-09-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_promptvariant_unique_prompt_variant_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptversion',
            name='model_name',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
    ]
