# Generated by Django 5.1.1 on 2024-09-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prompt_description'),
        ('project', '0003_project_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
