# Generated by Django 5.1.1 on 2024-09-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_segment_project'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promptversion',
            name='unique_prompt_version_name',
        ),
        migrations.RemoveField(
            model_name='promptversion',
            name='prompt',
        ),
        migrations.AddField(
            model_name='promptversion',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.promptvariant'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('variant', 'name'), name='unique_variant_version_name'),
        ),
    ]
