# Generated by Django 5.1.1 on 2024-10-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_clientpublickey_serverprivatekey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientpublickey',
            old_name='public_key',
            new_name='key',
        ),
        migrations.DeleteModel(
            name='ServerPrivateKey',
        ),
    ]
