# Generated by Django 5.1.1 on 2024-10-07 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_apikey_delete_clientpublickey_and_more'),
        ('project', '0004_remove_serverprivatekey_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='apikey',
            name='core_apikey_project_1be4e2_idx',
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['project', 'is_private'], name='core_apikey_project_f4a100_idx'),
        ),
    ]
