# Generated by Django 5.1 on 2024-08-27 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unique_key',
            field=models.CharField(max_length=512, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
