# Generated by Django 5.1.1 on 2024-09-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverprivatekey',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serverprivatekey',
            name='project',
        ),
        migrations.DeleteModel(
            name='ClientPublicKey',
        ),
        migrations.DeleteModel(
            name='ServerPrivateKey',
        ),
    ]
