# Generated by Django 5.1.1 on 2024-09-21 04:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userpermissionorganization',
            unique_together={('user', 'organization')},
        ),
    ]
