# Generated by Django 5.1.1 on 2024-09-21 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_organization', '0002_alter_userpermissionorganization_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='user_organization.UserPermissionOrganization', to=settings.AUTH_USER_MODEL),
        ),
    ]
